title: Derguns Town Status Information
baseURL: ''
languageCode: en
params:
  copyrightHolder: Derguns Town
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit Derguns Town'
    href='https://derguns.town/'>Dergun Town</a> is a free to play browser game
    where you can create and customise your character!
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit Dergun Town'
    href='https://derguns.town/'></a> systems operations.<br />Follow us <a
    class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Main
  logo: /images/clearstatus.svg
  meta_description: Main Status Page For Derguns.Town.
  shortDateFormat: '03:04 PM — Jan 2'
  systems:
    - description: The main Dergun Town site.
      link: 'https://derguns.town/'
      name: Website
    - description: Official Discord Server For Derguns Town
      link: 'https://discord.derguns.town'
      name: Discord Server
  timezoneString: ' UTC'
