title: Derguns Town Status Information
baseURL: ''
languageCode: en
params:
  copyrightHolder: Derguns Town
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit Derguns Town'
    href='https://derguns.town/'>Dergun Town</a> is a free to play browser game
    where you can create and customise your character!
  description_header: >-
    Here you can find information about our service status here.

    Join our <a class='text-grey-darkest' title='Join Derguns Town Discord'
    href='https://derguns.town/' Discord server</a> 
  eventsPerPage: 10
  groups:
    - Main
  logo: /images/uploads/logo-64.png
  meta_description: Main Status Page For Derguns.Town.
  shortDateFormat: '03:04 PM — Jan 2'
  systems:
    - description: The main Dergun Town site.
      link: 'https://derguns.town/'
      name: Website
    - description: Official Discord Server For Derguns Town
      link: 'https://discord.derguns.town'
      name: Discord Server
  timezoneString: ' UTC'
